# ---- Site basics ----
title: "Ask Surgeons — Attapur , Hyderabad"
tagline: "Clear answers • Trusted care"
description: "Hyderabad-based doctors directory, blog, and appointment info."
url: "https://asksurgeons.com"     # Change if needed
baseurl: ""       # Keep in sync with your repo/project path
site_phone: "+91 8062182411"
site_whatsapp: "+91 8062182411"
site_email: "asksurgeons@gmaill.com"
address: "hyderabad"
locale: en_IN
logo: /assets/site-images/logo.webp
banner: /assets/images/site-images/ask-surgeons-banner.jpeg

# ---- Author (used by seo tag in head.html) ----
author:
  name: "Ask Surgeons"

# ---- Build settings ----
markdown: kramdown
theme: null
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed

# Atom/RSS (jekyll-feed)
feed:
  path: atom.xml

# Sitemap
sass:
  style: compressed

# ---- Permalinks ----
permalink: /:categories/:title/


# ---- Collections (optional future) ----
# If later you create real profile pages in `_doctors/`
# collections:
#   doctors:
#     output: true
#     permalink: /doctors/:name/

# ---- Defaults ----
defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      comments: false

# ---- Excludes (tidy builds) ----
exclude:
  - README.md
  - node_modules
  - package.json
  - package-lock.json
  - Gemfile
  - Gemfile.lock

# ---- Data references ----
# You already have:
# _data/navigation.yml
# _data/doctors.yml
