# ─────────────────────────────────────────────────────────────
# Site basics
# ─────────────────────────────────────────────────────────────
title: "AskSurgeons.com"
description: >-
  Attapur | Hyderabad’s trusted platform for surgical guidance and second opinions.
  Read expert medical blogs from our doctors, then book consultations at
  app.asksurgeons.com.
url: "https://www.asksurgeons.com"   # full domain with protocol
baseurl: "/asksurgeons-site"                          # root
timezone: "Asia/Kolkata"
lang: "en-IN"

# ─────────────────────────────────────────────────────────────
# Build settings
# ─────────────────────────────────────────────────────────────
markdown: kramdown
highlighter: rouge
permalink: /:categories/:title/
sass:
  style: compressed

# Pagination (optional; used if you add a blog index)
paginate: 5
paginate_path: "/page:num/"

# Include additional folders (e.g., standalone pages in _pages/)
include:
  - _pages

# ─────────────────────────────────────────────────────────────
# Defaults (use our custom layouts/includes)
# ─────────────────────────────────────────────────────────────
defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: default        # we use our own _layouts/default.html
      author_profile: false   # not using theme profiles
      read_time: false
      comments: false
      share: false
      toc: false
      related: false
  - scope:
      path: ""
      type: pages
    values:
      layout: default

# ─────────────────────────────────────────────────────────────
# Site-wide variables (used in our includes/JS)
# ─────────────────────────────────────────────────────────────
theme_color: "#007bbf"
contact_number: "+91 8062182411"
contact_email: "asksurgeons@gmail.com"
clinic_number: "+91 7989676770"
address: "Attapur | Hyderabad"
brand:
  logo: /assets/images/site-images/logo.webp
  social_image: /assets/images/og.jpg

# Social (consumed by jekyll-seo-tag and your templates)
social:
  name: "AskSurgeons"
  links:
    - https://app.asksurgeons.com

# ─────────────────────────────────────────────────────────────
# Plugins (GitHub Pages–safe)
# ─────────────────────────────────────────────────────────────
plugins:
  - jekyll-paginate
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# ─────────────────────────────────────────────────────────────
# Collections (remove if unused)
# ─────────────────────────────────────────────────────────────
# If you later add a doctors profile collection, uncomment and create layouts.
# collections:
#   doctors:
#     output: true
#     permalink: /doctors/:path/

# ─────────────────────────────────────────────────────────────
# Exclude from build
# ─────────────────────────────────────────────────────────────
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - README.md

