name: Generate Author Pages

# Run when doctors data changes or manually
on:
  push:
    paths:
      - "_data/doctors.json"
  workflow_dispatch:

permissions:
  contents: write   # allow pushing commits

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: python -m pip install --upgrade pip

      - name: Run generator script
        run: |
          python scripts/generate_authors.py

      - name: Show git status
        run: git status --porcelain && git --no-pager diff --name-only || true

      - name: Commit & push generated authors (only if changed)
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add _authors || true
          if git diff --cached --quiet; then
            echo "No changes to commit."
          else
            git commit -m "chore: update generated _authors from _data/doctors.json"
            git push origin HEAD:HEAD
          fi
