name: Rename doctor images & update JSON

on:
  push:
    paths:
      - '_data/doctors.json'
      - 'doctors/images/**'
      - 'scripts/rename_images.py'
  workflow_dispatch:

permissions:
  contents: write  # needed to push commits

jobs:
  rename-images:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: true

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Show repo tree (debug)
        run: |
          echo "Root:"
          ls -la
          echo "_data:"
          ls -la _data || true
          echo "doctors/images:"
          ls -la doctors/images || true

      - name: Install dependencies (none required)
        run: echo "No pip packages required"

      - name: Run rename script
        run: |
          python3 scripts/rename_images.py
        env:
          LANG: C.UTF-8

      - name: Check git status
        run: |
          git status --porcelain
          git --no-pager diff --name-only || true

      - name: Commit & push changes (if any)
        run: |
          # configure git user
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          if [ -n "$(git status --porcelain)" ]; then
            git add -A
            git commit -m "chore: rename doctor images & update doctors.json [skip ci]"
            git push
            echo "Changes pushed."
          else
            echo "No changes to commit."
          fi
